-- Create Tablespace (if needed)
CREATE TABLESPACE vaultcore_data 
DATAFILE 'vaultcore01.dbf' SIZE 100M 
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- Create User
CREATE USER vaultcore_user IDENTIFIED BY VaultCore123
DEFAULT TABLESPACE vaultcore_data
QUOTA UNLIMITED ON vaultcore_data;

GRANT CONNECT, RESOURCE TO vaultcore_user;
GRANT CREATE SESSION TO vaultcore_user;

-- Connect as vaultcore_user
CONNECT vaultcore_user/VaultCore123@localhost:1521/VAULTCORE;

-- Create Users Table
CREATE TABLE users_vault (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    full_name VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Accounts Table
CREATE TABLE accounts_vault (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(20) UNIQUE NOT NULL,
    account_type VARCHAR2(20) NOT NULL CHECK (account_type IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE')),
    balance NUMBER(19,2) DEFAULT 0,
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create Ledger Entries Table (Immutable - Append Only)
CREATE TABLE ledger_entries_vault (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR2(50) NOT NULL,
    account_id NUMBER NOT NULL,
    amount NUMBER(19,2) NOT NULL CHECK (amount > 0),
    direction VARCHAR2(6) NOT NULL CHECK (direction IN ('DEBIT', 'CREDIT')),
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- Create Indexes for Performance
CREATE INDEX idx_ledger_account_date ON ledger_entries_vault(account_id, created_at DESC);
CREATE INDEX idx_ledger_transaction ON ledger_entries_vault(transaction_id);
CREATE INDEX idx_accounts_user ON accounts_vault(user_id);
CREATE INDEX idx_users_username ON users_vault(username);

-- Create Function to enforce double-entry balance
CREATE OR REPLACE TRIGGER trg_check_transaction_balance
BEFORE INSERT ON ledger_entries_vault
FOR EACH ROW
DECLARE
    v_debit_total NUMBER;
    v_credit_total NUMBER;
BEGIN
    -- This trigger would need to check the entire transaction
    -- For simplicity, we'll enforce at application level
    NULL;
END;
/

-- Create Sequence for transaction IDs
CREATE SEQUENCE seq_transaction_id
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create View for account balances
CREATE OR REPLACE VIEW v_account_balances AS
SELECT 
    a.id,
    a.account_number,
    a.account_type,
    a.user_id,
    a.balance as current_balance,
    NVL((SELECT SUM(amount) FROM ledger_entries_vault WHERE account_id = a.id AND direction = 'DEBIT'), 0) as total_debits,
    NVL((SELECT SUM(amount) FROM ledger_entries_vault WHERE account_id = a.id AND direction = 'CREDIT'), 0) as total_credits
FROM accounts a;

-- Insert sample data
INSERT INTO users_vault (username, password, email, full_name) 
VALUES ('john_doe', '$2a$10$YourHashedPasswordHere', 'john@example.com', 'John Doe');

INSERT INTO users_vault (username, password, email, full_name) 
VALUES ('jane_smith', '$2a$10$YourHashedPasswordHere', 'jane@example.com', 'Jane Smith');

-- Create accounts for users
INSERT INTO accounts_vault (account_number, account_type, balance, user_id) 
VALUES ('ACC1234567890', 'ASSET', 5000.00, 1);

INSERT INTO accounts (account_number, account_type, balance, user_id) 
VALUES ('ACC0987654321', 'ASSET', 2500.00, 2);

-- Commit the transactions
COMMIT;
